name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint Resource
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: iLLeniumStudios/fivem-lua-lint-action@v2
        with:
          capture: "junit.xml"
          args: "-t --formatter JUnit"
          extra_libs: mysql+polyzone
      - name: Generate Lint Report
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "**/junit.xml"
          check_name: Linting Report
          comment_mode: update last
          fail_on: nothing
